# fly.toml file generated for shit-your-pants-its-so-good-node-app on 2023-04-14T13:30:46-04:00

app = "shit-your-pants-its-so-good-node-app"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mia"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
